######################################################################
# GitLab CI build script for the ClammyScan project                   #
######################################################################
image: kpmeen/docker-scala-sbt

variables:
  DOCKER_DRIVER: overlay
  # Setting specific folder for sbt-coursier to cache artifacts
  COURSIER_CACHE: "/root/cache/coursier"
  CLAM_HOST: clammy
  CLAM_PORT: 3310

cache:
  untracked: true
  paths:
    - cache

services:
  - name: kpmeen/docker-clamav
    alias: clammy
    command: ["-m", "2M"]

stages:
  - stylecheck
  - test
  - release

check style and formatting:
  stage: stylecheck
  script:
    - sbt clean scalastyle scalafmt
    - git diff --exit-code || (echo "ERROR Code formatting check failed, see differences above."; false)

run test suites for 2.12:
  stage: test
  coverage: '/\[info]\sAll\sdone\.\sCoverage\swas\s\[(.*)%\]/'
  script:
    # Build the project
    - sbt clean coverage test coverageReport
    - sbt coverageAggregate codacyCoverage

run test suites for 2.11:
  stage: test
  script:
    # Build the project
    - sbt "++ 2.11.11" test

