######################################################################
# GitLab CI build script for the ClammyScan project                   #
######################################################################
image: kpmeen/docker-clammyscan-builder

variables:
  DOCKER_DRIVER: overlay
  # Setting specific folder for sbt-coursier to cache artifacts
  COURSIER_CACHE: "/root/cache/coursier"

cache:
  untracked: true
  paths:
    - cache

stages:
  - stylecheck
  - test
  - release

check style and formatting:
  stage: stylecheck
  script:
    - sbt clean scalastyle scalafmt
    - git diff --exit-code || (echo "ERROR Code formatting check failed, see differences above."; false)

run test suites:
  stage: test
  coverage: '/\[info]\sAll\sdone\.\sCoverage\swas\s\[(.*)%\]/'
  script:
    # Start clamav
    - /bootstrap.sh
    # Build the project
    - sbt clean coverage test coverageReport
    - sbt coverageAggregate codacyCoverage

